CREATE DATABASE IF NOT EXISTS twitter_replica;

USE twitter_replica;

CREATE TABLE IF NOT EXISTS usuarios(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(100) NOT NULL,
	email VARCHAR(110) NOT NULL,
	senha VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS tweets(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	id_usuario INT NOT NULL,
	tweet VARCHAR(280) NOT NULL,
	data DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS seguidores(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	id_usuario INT NOT NULL,
	id_usuario_seguidor INT NOT NULL
);