CREATE DATABASE IF NOT EXISTS twitter_replica;

CREATE TABLE IF NOT EXISTS usuarios(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(100) NOT NULL,
	email VARCHAR(110) NOT NULL,
	senha VARCHAR(32) NOT NULL
);