<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/style.css">
    <title>Twitter</title>
</head>
<body>
    
    <main id="home">

        <div id="container">
            <div id="image"> 
                <img src="img/background-index.png" alt="Background image" id="background">
                <img src="img/bird-svg.svg" alt="" id="big-bird">
            </div>
            <div id="content">
            <form action="/logar" method="POST">
                <input type="text" name="email" id="email" placeholder="E-mail"><br>
                <input type="password" name="senha" id="senha" placeholder="Senha"><br>
                <input type="submit" value="Logar">
            </form>
            <a href="/inscreverse">Registrar</a>
            <?php
                //Caso autenticação não ocorra será informado está mensagem de erro
                if(isset($this->view->login)){
                    echo '<h1>' . $this->view->login . '</h1>';
                }
            ?>
            </div>
        </div>

    </main>

    <footer>
        <span>Sobre</span>
        <span>Central de Ajuda</span>
        <span>Termos de Serviço</span>
        <span>Política de Privacidade</span>
        <span>Política de cookies</span>
        <span>Acessibilidade</span>
        <span>Informações de Anúncios</span>
        <span>Blog</span>
        <span>Status</span>
        <span>Carreiras</span>
        <span>Recursos da marca</span>
        <span>Publicidade</span>
        <span>Marketing</span>
        <span>Twitter para Empresas</span>
        <span>Desenvolvedores</span>
        <span>Diretório</span>
        <span>Configurações</span>
        <span>
            © 2022 Twitter, Inc.</span>
    </footer>
</body>
</html>