<?php
    echo '<h1>Timeline de ' . $_SESSION['nome'] . '</h1>';
?>
<a href="/sair">Sair</a>

<form action="/tweet" method="POST">
    <textarea name="tweet" id="tweet" cols="30" rows="10"></textarea>
    <input type="submit" value="Twittar">
</form>

<hr>

<?php

    foreach($this->view->tweets as $key => $tweet){
        echo '<h1>' . $tweet['nome'] . '</h1>';
        echo '<p>' . $tweet['tweet'] . '</p>';
        echo '<p>Data:' . $tweet['data'] . '</p>';
        if($_SESSION['id'] == $tweet['id_usuario']){
            ?>
            <form action="/remover?id=<?php echo $tweet['id']; ?>" method="POST">
                <button type="submit">REMOVER</button>
            </form>
            <?php
        }
        echo '<hr>'; 
    }

?>

<h1>Talvez você conheça!</h1>
<a href="/buscar_conhecidos">Busque por pessoas conhecidas</a>